apiVersion: v1
kind: Service
metadata:
  name: shconnect-deployment
spec:
  selector:
    app: shconnect-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4443
  #selector:
    #run: shconnect-deployment
  selector:
    app: shconnect-deployment
  selector:
    app: shconnect-deployment
  type: LoadBalancer
